config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "scores#top"
  resources :scores do
    resources :comments, only: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord


belongs_to :score
belongs_to :user

validates :text, presence: true

end

app/models/occupation.rb
class Occupation < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '店員' },
    { id: 3, name: '会員' },
  ]

  include ActiveHash::Associations
  has_many :users

  
end

app/models/profile.rb
class Profile < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '東京ボール' },
    { id: 3, name: '長野ボール' },
    { id: 4, name: '福島ボール' },
  ]
  include ActiveHash::Associations
  has_many :users

end

app/models/schedule.rb
class Schedule < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '第1週目' },
    { id: 3, name: '第2週目' },
    { id: 4, name: '第3週目' },
    { id: 5, name: '第4週目' },
  ]
  include ActiveHash::Associations
  has_many :scores

end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_one_attached :image

  
  with_options presence: true do
   validates :schedule_id, numericality: { other_than: 1 }
   validates :score, inclusion: {in: (1..300)}
  end
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :schedule
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  with_options presence: true do
   validates :name
   validates :profile_id, numericality: { other_than: 1 }
   validates :occupation_id, numericality: { other_than: 1 }
  end

  has_many :scores
  has_many :comments
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :occupation
  belongs_to_active_hash :profile
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile_id, :occupation_id])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
  end

  

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to score_path(@comment.score)
    else
      # @score = @comment.score
      # @comments = @score.comments
      redirect_to root_path
    end
  end 
  
  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, score_id: params[:score_id])
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index
    @scores = Score.all.order(score: :DESC).page(params[:page]).per(3)
  end

  def top
    @scores = Score.all.order(score: :DESC)
  end

  def new
    @score = Score.new
    if current_user.occupation_id != 2
      redirect_to root_path
    end
  end

  def create
    @score = Score.new(score_params)
    if @score.save
      redirect_to root_path
    else 
      render :new
    end  
  end

  def show
    @score = Score.find(params[:id])
    @comment = Comment.create
    @comments = Comment.all
  end  

  def edit
    @score = Score.find(params[:id])
  end
  
  def update
    @score = Score.find(params[:id])
    if @score.update(score_params)
      redirect_to score_path(@score.id)
    else
      render :edit
    end  
  end 
  
  def destroy
    @score = Score.find(params[:id])
    @score.destroy
    redirect_to root_path
  end  



  private
  def score_params
    params.require(:score).permit(:schedule_id, :score, :image).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Free Time Competition</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo2.png", class: :logo), root_path %>
          </div>
          
          <% if user_signed_in? %>
             <div class="nav__right"> 
               <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
               <% if current_user.occupation_id == 2 %>
               <%= link_to "Your Score", new_score_path, class: :nav__btn %>
               <% end %>
             </div> 
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
          <% if user_signed_in? %>
           <div class="greeting"> 
             <%# こんにちは、 %>
             <%= link_to "#{current_user.name}", root_path, class: :greeting__link%>
           </div> 
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © Free Time Competition All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/scores/_form.html.erb
<%= form_with model: @score, local: true do |f|%>
  <div class="field">
    <%= f.label :schedule, "This Weekday Competition" %><br />
    <%= f.collection_select(:schedule_id, Schedule.all, :id, :name, {}, {class: :form__text}) %>
     <%# <%= f.text_field :schedule_id %>  
  </div>

  <div class="field">
    <%= f.label :score, "Your's Score" %><br />
    <%= f.text_area :score, class: :form__text %>
  </div>

  
  <div class="field">
    <%= f.label :image, "Your's Photo" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>


<%# <div class="field"> %>
    <%# <%= f.label :ranking, "Your's Ranking" %><br /> 
    <%# <%= f.text_area :ranking, class: :form__text %> 
  <%# </div> %>

app/views/scores/_score.html.erb
<div class="card">
  
   <h2><%= "スコア#{score.score}点" %></h2>
   <%= link_to image_tag(score.image, class: :card__img ),score_path(score.id) %>
  <div class="card__body">
    <%# <%= link_to score.schedule_id, score_path(score.id), class: :card__title%> 
    
    <%# <p class="card__summary"> %>
      <%= "#{score.user.name}さん" %>
      <%= "(#{score.user.profile.name}所属)" %>
    <%# </p> %>

    </div>
    
</div>

app/views/scores/edit.html.erb
<div class="main">
  
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">Edit your score</h2>
      <%= render partial: "form", locals: { score: @score } %>
    </div>
  </div>
</div>

app/views/scores/index.html.erb
<main class="main">
  <div class="inner">
    <div class="card__wrapper">
      
      <%= render partial: 'score', collection: @scores %>
    </div>
    <%# <%= image_tag "yellow_chair.jpg" %> 
  </div>
  <%= paginate @scores %>
</main>

app/views/scores/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">Please post your score</h2>
        <%= render partial: "form", locals: { score: @score } %>
    </div>
  </div>
</div>

app/views/scores/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%# <%= @score.schedule_id %> 
      </p>
      <%= link_to " #{@score.user.name}さん", root_path, class: :prototype__user %>
      <% if current_user == @score.user%>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_score_path(@score), class: :prototype__btn %>
          <%= link_to "削除する", score_path(@score), method: :delete, class: :prototype__btn %>
        </div>
      <% end %>
      <div class="prototype__image">
        <%= image_tag @score.image %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title"></p>
          <p class="detail__message">
            <%="スコア#{ @score.score }点" %>
          </p>
        </div>
        <%# <div class="prototype__detail"> %>
          <%# <p class="detail__title">Your Ranking</p> %>
          <%# <p class="detail__message"> %>
            <%# <%= @score.ranking %> 
          <%# /</p> %>
        <%# </div> %>
        
      </div>
 


      <div class="prototype__comments">
        <% if user_signed_in? %>
         <%= form_with(model: [@score, @comment], local: true) do |f| %>
            <div class="field">
              <%= f.label :text, "#{@score.user.name}さんのコメント" %>
              <%= f.text_field :text %>
            </div>
            <div class="actions">
               <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %> 
        <% end %>  
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <% @comments.each do |comment| %>
            <li class="comments_list">
               <%= comment.text %>
              <%= link_to comment.user.name, user_path(comment.user), class: :comment_user %>
            </li>
            <% end %> 
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>

        
        
        
      </div>
    </div>
  </div>
</main>

app/views/scores/top.html.erb
<main class="main">
  
  
  <div class="inner">
    <%# <div class="title-contents"> %>
    <%# </div> %>
    <div class="card__wrapper">
    
    <% if @scores.empty? %>
     <h1>おはよう！</h1>
    <% else %>
     <div class="yama"><h1><%= "今週の第一位#{@scores[0].user.name}さん"%></h1>
     
     <h1 class="yama1"><%= "(#{@scores[0].user.profile.name}所属)" %></h1></div>
     <h2><%= @scores[0].schedule.name %></h2>
    <%= link_to image_tag @scores[0].image %><br>  
    
   
      

      <h1><%="スコア#{ @scores[0].score }点"%></h1> 
    <% end %>
        
    </div>
  </div>

  <h1><%= link_to "🎳スコア一覧🎳" ,scores_path %></h1>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.name}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile.name %></td>
          </tr>
          <%# <tr> %>
            <%# <th class="table__col1">所属</th> %>
            <%# <td class="table__col2"><%= @user.occupation %>
            <%# </td> %> 
          <%# </tr> %>
          
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんの今週のスコアー"%>
      </h2>
      <div class="user__card">
        <%= render partial: 'scores/score', collection: @user.scores %>
      </div>
    </div>
  </div>
</div>